# Generated by Django 4.0.6 on 2022-07-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.EmailField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
