# Generated by Django 4.0.6 on 2022-08-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('news_name', models.CharField(max_length=256)),
                ('news_href', models.CharField(max_length=256)),
            ],
        ),
    ]
